spring.application.name=api

# misma database que current_database()
spring.datasource.url=jdbc:postgresql://localhost:5432/Atlas
spring.datasource.username=postgres
spring.datasource.password=root

# agregar un seed que se ejecute al inicio de la aplicación
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# # Hibernate NO crea tablas. Flyway ya tiene V1__init.sql
# spring.jpa.hibernate.ddl-auto=validate

# # hábito sano; hoy no cambia nada visible
# spring.jpa.open-in-view=false

# # Flyway está en el pom; esto lo deja explícito
# spring.flyway.enabled=true

# # interruptor "estoy en local". El seed de verdad viene después
# spring.profiles.active=dev